#!/bin/bash
# regenerate_slack_webhook.sh - Guide to regenerate compromised Slack webhook

echo "=========================================="
echo "SLACK WEBHOOK REGENERATION SCRIPT"
echo "=========================================="
echo ""
echo "Your webhook was exposed to a potentially malicious site."
echo "You MUST regenerate it NOW."
echo ""
echo "STEP 1: Open Slack in browser"
echo "   URL: https://api.slack.com/apps"
echo ""
echo "STEP 2: Find your app (AICenterPlus or similar)"
echo "   Click on it"
echo ""
echo "STEP 3: Delete old webhook"
echo "   Go to: Incoming Webhooks"
echo "   Find: #ai-war-room webhook"
echo "   Click: Delete"
echo "   Confirm: Yes, delete"
echo ""
echo "STEP 4: Create new webhook"
echo "   Click: Add New Webhook to Workspace"
echo "   Select: #ai-war-room channel"
echo "   Click: Allow"
echo ""
echo "STEP 5: Copy new webhook URL"
echo "   It looks like: https://hooks.slack.com/services/T.../B.../..."
echo "   Click: Copy"
echo ""
echo "STEP 6: Give new URL to Kimi Claw"
echo "   Send it in a secure way (this chat is compromised)"
echo "   Or: Save it to a file I can read"
echo ""
echo "STEP 7: Update config files"
echo "   I will update: ai-bridge.sh"
echo "   I will update: manual/"
echo "   I will update: skills/ai-bridge/"
echo ""
echo "=========================================="
echo "URGENT: Do this NOW"
echo "=========================================="
